# Fase 1 · Análisis Exploratorio de Datos (EDA)

## Objetivo

El objetivo de esta fase es realizar una exploración inicial de los distintos datasets relacionados con la serie de *Friends*, procedentes tanto de fuentes públicas (Kaggle) como de datasets generados y enriquecidos mediante técnicas de IA. Esta revisión permite comprender su estructura, evaluar su calidad y detectar posibles inconsistencias que puedan afectar a las siguientes fases del proyecto.

En esta etapa nos centramos en:

- identificar los datasets disponibles y sus variables principales,
- analizar dimensiones, tipos de datos y coherencia interna,
- detectar valores nulos, duplicados y problemas de calidad,
- explorar variables clave para entender el comportamiento del dataset,
- y anticipar necesidades de limpieza, normalización y transformación.

Este análisis proporciona una base sólida para definir la estrategia de preparación de datos en la fase ETL.

In [34]:
# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación de librerías
import pandas as pd
import numpy as np

# Importación del módulo de transformación personalizado
from src.etl import transform as trans

# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

## 1. Carga de los datasets

Se cargan los distintos archivos que contienen información sobre personajes, guiones, temporadas y métricas de diálogo.
Cada uno aporta una dimensión diferente al análisis.

In [35]:
df_bodas_divorcios = pd.read_csv("../data_raw/bodas_divorcios_ross.csv")
df_cameos = pd.read_csv("../data_raw/cameos_friends_completo.csv")
df_emotions = pd.read_csv("../data_raw/friends_emotions.csv")
df_epiv2 = pd.read_csv("../data_raw/friends_episodes_v2.csv")
df_epiv3 = pd.read_csv("../data_raw/friends_episodes_v3.csv", encoding='latin-1')
df_escenarios = pd.read_csv("../data_raw/friends_escenarios.csv")
df_info = pd.read_csv("../data_raw/friends_info.csv")
df_quotes = pd.read_csv("../data_raw/friends_quotes.csv")
df_friends = pd.read_csv("../data_raw/friends.csv")
df_songs = pd.read_csv("../data_raw/phoebe_buffay_songs_v2.csv")
df_pato_pollito = pd.read_csv(
    "../data_raw/apariciones_detalladas_pato_y_pollito(1).csv", 
    sep=';', 
    encoding='latin-1'
)

### Procedemos con la exploración de cada fichero

#### 1. Dataset: Bodas_divorcios_ross
El dataset contiene datos registran el historial de matrimonios y divorcios de los personajes de la serie Friends (haciendo especial honor a los múltiples matrimonios de Ross Geller).

En este bloque se revisará la estructura general del dataset, la presencia de valores nulos, la existencia de duplicados y la variable Personaje, ya que será la variable categórica principal que articulará el análisis del historial de eventos del proyecto.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_bodas_divorcios)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Personaje  6 non-null      str
 1   Evento     6 non-null      str
 2   Temporada  6 non-null      int64
 3   Detalle    6 non-null      str
dtypes: int64(1), str(3)
memory usage: 324.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

          count unique                                    top freq
Personaje     6      3                          Carol Willick    2
Evento        6      2                                   Boda    3
Detalle       6      6  Ocurre antes del piloto (flashbacks).    1

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

           count  mean   std  min   25%  50%  75%  max
Temporada    6.0   3.5  2.43  0.0  1.75  4.5  5.0  6.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
6 filas
4 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Personaje,Evento,Temporada,Detalle
3,Emily Waltham,Divorcio,5,Emily le pide no ver a Rachel y él no cumple.
4,Rachel Green,Boda,5,Se casan borrachos en Las Vegas.
2,Emily Waltham,Boda,4,Boda en Londres; Ross dice el nombre de Rachel.
0,Carol Willick,Boda,0,Ocurre antes del piloto (flashbacks).
1,Carol Willick,Divorcio,1,Ella descubre que es lesbiana.

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_bodas_divorcios)

Columna: Personaje
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Carol Willick', 'Emily Waltham', 'Rachel Green']
Length: 3, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 3
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Evento
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Boda', 'Divorcio']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 4
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Temporada
 ----------------------------------------------------------------------------------------------------
Valores unicos: [0 1 4 5 6]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Detalle
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[            'Ocurre antes del piloto (flashbacks).',
                    'Ella descubre que es lesbiana.',
   'Boda en Londres; Ross dice el nombre de Rachel.',
     'Emily le pide no ver a Rachel y él no cumple.',
                  'Se casan borrachos en Las Vegas.',
 'Ross intenta ocultar que no tramitó la anulación.']
Length: 6, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (bodas_divorcios_ross)

El dataset presenta una estructura simple, 100% limpia y libre de valores nulos, donde la redundancia identificada en Personaje y Evento no representa un error ni afecta los resultados, sino que cumple un fin estrictamente informativo y relacional para mapear las transiciones de cada suceso. Posibilidad de cambiar los nombres de las columnas al inglés y en minúculas.

#### 2. Dataset: cameos_friends_completo
Este nuevo archivo (cameos_friends_completo.csv) contiene el registro de las apariciones de actores invitados y celebridades en la serie Friends.

En este bloque se revisará la estructura general del dataset, la presencia de valores nulos y la existencia de duplicados.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_cameos)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Actor/Actriz           25 non-null     str
 1   Personaje              25 non-null     str
 2   Descripción/Temporada  25 non-null     str
dtypes: str(3)
memory usage: 732.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

,count,unique,top,freq
Actor/Actriz,25,25,Brad Pitt,1
Personaje,25,25,Will Colbert,1
Descripción/Temporada,25,25,Antiguo compañero que odiaba a Rachel (T8),1

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:
Nota: El DataFrame no contiene variables cuantitativas (numéricas) para analizar.
----------------------------------------------------------------------------------------------------
La forma del dataframe es:
25 filas
3 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Actor/Actriz,Personaje,Descripción/Temporada
9,Sean Penn,Eric,Novio de Ursula que sale con Phoebe (T8)
20,Jeff Goldblum,Leonard Hayes,Director de una obra donde audiciona Joey (T9)
10,Ben Stiller,Tommy,Novio de Rachel con problemas de ira (T3)
7,George Clooney,Dr. Michael Mitchell,Médico que atiende a Rachel (T1)
1,Bruce Willis,Paul Stevens,Padre de Elizabeth y novio de Rachel (T6)

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_cameos)

Columna: Actor/Actriz
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[            'Brad Pitt',          'Bruce Willis',         'Julia Roberts',
         'Charlie Sheen',          'Danny DeVito',        'Robin Williams',
         'Billy Crystal',        'George Clooney',             'Noah Wyle',
             'Sean Penn',           'Ben Stiller',          'Winona Ryder',
           'Gary Oldman',     'Reese Witherspoon',   'Christina Applegate',
          'Alec Baldwin', 'Jean-Claude Van Damme',           'Hugh Laurie',
    'Freddie Prinze Jr.',        'Dakota Fanning',         'Jeff Goldblum',
        'Susan Sarandon',           'Jon Favreau',           'Hank Azaria',
       'Kathleen Turner']
Length: 25, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Personaje
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[        'Will Colbert',         'Paul Stevens',           'Susie Moss',
                 'Ryan',                  'Roy',                'Tomas',
                  'Tim', 'Dr. Michael Mitchell',    'Dr. Jeffrey Rosen',
                 'Eric',                'Tommy',    'Melissa Warburton',
       'Richard Crosby',          'Jill Greene',           'Amy Greene',
               'Parker',             'Él mismo',       'Pasajero avión',
                'Sandy',            'Mackenzie',        'Leonard Hayes',
     'Jessica Lockhart',          'Pete Becker',                'David',
         'Charles Bing']
Length: 25, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Descripción/Temporada
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                  'Antiguo compañero que odiaba a Rachel (T8)',
                    'Padre de Elizabeth y novio de Rachel (T6)',
                       'Compañera de primaria de Chandler (T2)',
             'Marinero novio de Phoebe que tiene varicela (T2)',
         'El stripper sensible en la despedida de Phoebe (T10)',
      'Cliente del Central Perk en una escena improvisada (T3)',
                       'Amigo de Tomas en el Central Perk (T3)',
                             'Médico que atiende a Rachel (T1)',
                             'Médico compañero de Clooney (T1)',
                     'Novio de Ursula que sale con Phoebe (T8)',
                    'Novio de Rachel con problemas de ira (T3)',
                       'Amiga de la universidad de Rachel (T7)',
                     'Actor que escupe al hablar con Joey (T7)',
                                 'Hermana menor de Rachel (T6)',
                                   'Hermana de Rachel (T9/T10)',
               'Novio de Phoebe extremadamente entusiasta (T8)',
                     'Actor en la película que rueda Joey (T2)',
     'Hombre que se queja de Rachel en el vuelo a Londres (T4)',
                              'El niñero sensible de Emma (T9)',
 'Niña que vive en la casa que compran Monica y Chandler (T10)',
               'Director de una obra donde audiciona Joey (T9)',
                           'Actriz de 'Days of Our Lives' (T7)',
      'Millonario novio de Monica que quiere ser luchador (T3)',
     'El científico novio de Phoebe que se va a Minsk (Varios)',
                                       'Padre de Chandler (T7)']
Length: 25, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (cameos_friends_completo)

El dataset presenta una estructura simple, con un estado de limpieza óptimo al registrar un 0% de valores nulos y cero registros duplicados. No obstante, desde la perspectiva de ingeniería de datos, se identifica la necesidad de aplicar una transformación para disociar la columna Descripción/Temporada en dos atributos independientes, permitiendo así aislar la variable temporal para su correcto análisis cuantitativo.

#### 3. Dataset: friends_emotions

A diferencia de los anteriores, este set de datos está diseñado para realizar análisis agregados complejos, tales como evaluar la evolución del estado emocional de los personajes a lo largo de las temporadas o identificar las escenas con mayor intensidad dramática o cómica. Posibilidad de cambiar los nombres al inglés y en misnúsculas.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_emotions)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 12606 entries, 0 to 12605
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   season     12606 non-null  int64
 1   episode    12606 non-null  int64
 2   scene      12606 non-null  int64
 3   utterance  12606 non-null  int64
 4   emotion    12606 non-null  str
dtypes: int64(4), str(1)
memory usage: 492.6 KB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

         count unique      top  freq
emotion  12606      7  Neutral  3776

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

             count   mean   std  min  25%   50%   75%   max
season     12606.0   2.57  1.11  1.0  2.0   3.0   4.0   4.0
episode    12606.0  13.19  7.20  1.0  7.0  14.0  20.0  25.0
scene      12606.0   7.52  4.43  1.0  4.0   7.0  11.0  29.0
utterance  12606.0   9.80  5.94  1.0  5.0   9.0  14.0  30.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
12606 filas
5 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

       season  episode  scene  utterance emotion
9618        4        2     12          6  Scared
11472       4       17     10         18  Scared
8835        3       23      3         11  Scared
12515       4       24     16         11  Scared
7808        3       16      9          5     Sad

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_emotions)

Columna: season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1 2 3 4]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12602
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: episode
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12581
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: scene
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 4  5  7  8 10 12 13 15  1  2  6  9 11 14  3 16 17 20 18 19 21 22 25 29
 23]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12581
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: utterance
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19  2  9 20 21 22 23 25
 24 26 27 29 28 30]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12576
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: emotion
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Mad', 'Neutral', 'Joyful', 'Scared', 'Sad', 'Powerful', 'Peaceful']
Length: 7, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12599
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_emotions)

El dataset presenta una estructura limpia y libre de valores nulos, acotando su alcance analítico exclusivamente a las cuatro primeras temporadas de la serie. Asimismo, la presencia de registros duplicados en las variables de temporada, episodio, escena e incluso en las emociones no interfiere ni afecta negativamente el análisis, ya que responde a la naturaleza lógica y repetitiva de las interacciones y estados anímicos a lo largo de los capítulos, actuando de forma puramente informativa para el estudio de patrones.

#### 4. Dataset: friends_episodes_v2

Este dataset permite realizar análisis de rendimiento reales (por ejemplo, evaluar la evolución de las calificaciones (Stars) a lo largo de los años o identificar quién fue el director con los episodios mejor valorados por el público).

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_epiv2)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year_of_prod   235 non-null    int64
 1   Season         235 non-null    int64
 2   Episode_Title  235 non-null    str
 3   Duration       235 non-null    int64
 4   Summary        235 non-null    str
 5   Director       235 non-null    str
 6   Stars          235 non-null    float64
 7   Votes          235 non-null    int64
dtypes: float64(1), int64(4), str(3)
memory usage: 14.8 KB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

,count,unique,top,freq
Episode_Title,235,230,The One with Ross's Wedding,2
Summary,235,235,Ross finds out his ex-wife is pregnant. Rachel...,1
Director,235,28,Kevin Bright,54

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

              count     mean     std     min     25%     50%     75%      max
Year_of_prod  235.0  1998.98    2.83  1994.0  1997.0  1999.0  2001.0   2004.0
Season        235.0     5.40    2.81     1.0     3.0     5.0     8.0     10.0
Duration      235.0    22.34    1.52    22.0    22.0    22.0    22.0     30.0
Stars         235.0     8.46    0.40     7.2     8.2     8.4     8.7      9.7
Votes         235.0  3352.29  824.21  2557.0  2885.5  3147.0  3579.5  10381.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
235 filas
8 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Year_of_prod,Season,Episode_Title,Duration,Summary,Director,Stars,Votes
134,2000,6,The One That Could Have Been,30,When Rachel hears Barry and Mindy are getting ...,Michael Lembeck,8.5,3097
213,2003,9,The One with the Fertility Test,22,"Still unable to conceive, Monica and Chandler ...",Gary Halvorson,8.2,2557
157,2001,7,The One Where Rosita Dies,22,Rachel breaks Joey's armchair. Phoebe takes a ...,Stephen Prime,8.4,2819
45,1996,2,The One with the Chicken Pox,22,Phoebe catches chicken pox just as an old flam...,Michael Lembeck,8.1,3360
88,1998,4,The One with the Free Porn,22,Chandler and Joey discover that they're gettin...,Michael Lembeck,8.6,3212

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_epiv2)

Columna: Year_of_prod
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 224
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 225
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Episode_Title
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[          'The One with the Sonogram at the End',
                         'The One with the Thumb',
             'The One with George Stephanopoulos',
 'The One with the East German Laundry Detergent',
                          'The One with the Butt',
                      'The One with the Blackout',
                  'The One Where Nana Dies Twice',
               'The One Where Underdog Gets Away',
                        'The One with the Monkey',
                         'The One with Mrs. Bing',
 ...
             'The One with the Late Thanksgiving',
                  'The One with the Birth Mother',
             'The One Where Chandler Gets Caught',
               'The One Where the Stripper Cries',
                  'The One with Phoebe's Wedding',
               'The One Where Joey Speaks French',
                 'The One with Princess Consuela',
                     'The One Where Estelle Dies',
         'The One with Rachel's Going Away Party',
                                   'The Last One']
Length: 230, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 5
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Duration
 ----------------------------------------------------------------------------------------------------
Valores unicos: [22 30 24 27 26 23]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 229
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Summary
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                                                               'Ross finds out his ex-wife is pregnant. Rachel returns her engagement ring to Barry. Monica becomes stressed when her and Ross's parents come to visit.',
                                                  'Monica becomes irritated when everyone likes her new boyfriend more than she does. Chandler resumes his smoking habit. Phoebe is given $7000 when she finds a thumb in a can of soda.',
                                  'Joey and Chandler take Ross to a hockey game to take his mind off the anniversary of the first time he slept with Carol, while the girls become depressed when they realize they don't have a 'plan'.',
           'Eager to spend time with Rachel, Ross pretends his washroom is rat-infested so he can join her at the laundromat. Meanwhile, Joey has Monica pose as his girlfriend, and Chandler struggles to break up with his girlfriend.',
                     'Monica's obsessiveness is put to the test after Rachel cleans the apartment. Joey lands a film role as Al Pacino's butt double. Chandler enjoys a relationship with all of the fun but none of the responsibility.',
                                                                                          'When New York suffers from a blackout, Ross tries to tell Rachel that he likes her, and Chandler gets stuck in an ATM vestibule with a model.',
                                                                                                                          'Monica and Ross mourn the loss of their grandmother. Chandler is shocked to find that people think he is gay.',
                                                                                                                                  'The gang's plans for Thanksgiving go awry after they get locked out of Monica and Rachel's apartment.',
                                                           'The gang make (and break) a pact not to bring dates to their New Years Eve party. Phoebe starts dating a scientist. Ross compensates for his loneliness by getting a monkey.',
                                                                              'Chandler's flamboyant romance-novelist mother comes to visit, and Joey catches her kissing Ross. Meanwhile, Monica and Phoebe fight over a guy in a coma.',
 ...
     'After Rachel confirms Joey is more mature in relationships, Phoebe presents him to another friend as date, Sarah, who fails alas to respect his primordial rule by touching food in his plate...                See full summary »',
          'Chandler and Monica have decided they want to raise their offspring in a suburban house and even find a perfect one in Westchester. Rachel and Phoebe see Chandler enter a car with his ...                See full summary »',
                                                    'Old secrets come to light when Ross and Chandler attend a college reunion. Monica and Rachel throw Phoebe a bachelorette party. Joey appears as a celebrity partner on a game show.',
                                                                                                                                                                                'Chaos ensues as Phoebe and Mike prepare to get married.',
                                                                                                  'Phoebe tries to teach Joey to speak French for an audition; Ross and Rachel head out to Long Island after her dad has a heart attack.',
      'When Phoebe goes to get her name changed she realizes she can change it to anything she wants, so she changes it to Princess Consuela Banana Hammock, to Mike's displeasure. Chandler finds ...                See full summary »',
                                                                                              'Ross tries to get Rachel to go back to Ralph Lauren, Joey doesn't know that his agent has died, and Monica and Chandler bump into Janice.',
                                                                                                                                       'The gang throws Rachel a goodbye party, during which she says goodbye to everybody individually.',
     'Erica gives birth to the baby that Monica and Chandler are adopting. However, there's one small added surprise. Meanwhile, Ross and Rachel sleep together one last time before Rachel leaves ...                See full summary »',
 'Phoebe races Ross to the airport in a bid to stop Rachel from leaving for Paris. Monica and Chandler pack up their apartment ahead of their move to their new house, and Joey buys Chandler a new chick and duck as a leaving present.']
Length: 235, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Director
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[       'James Burrows',        'Pamela Fryman',       'Arlene Sanford',
         'Peter Bonerz',         'Paul Lazarus',         'Alan Myerson',
      'Michael Lembeck',         'Gail Mancuso',         'Robby Benson',
         'Kevin Bright',     'Ellen Gittelsohn',       'Mary Kay Place',
      'Thomas Schlamme',      'Steve Zuckerman',         'Terry Hughes',
            'Sam Simon',       'Shelley Jensen',       'Gary Halvorson',
      'David Steinberg', 'Dana De Vally Piazza',        'Joe Regalbuto',
          'Andrew Tsao',         'Todd Holland',      'David Schwimmer',
            'Ben Weiss',        'Stephen Prime',         'Sheldon Epps',
   'Roger Christiansen']
Length: 28, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 207
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Stars
 ----------------------------------------------------------------------------------------------------
Valores unicos: [8.1 8.2 8.5 9.  8.7 8.3 8.8 7.9 8.9 8.4 8.  8.6 9.4 9.1 9.5 7.2 9.2 9.7
 7.4 9.3 7.5 7.8]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 213
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: Votes
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 4888  4605  4468  4438  4274  5469  4156  4038  4064  3996  3926  4172
  3866  3915  3834  3883  4340  3734  3736  3769  3720  3919  4187  3814
  3669  3676  3555  3550  3822  4319  3581  3444  3591  3524  3723  3864
  5736  3928  3435  3407  3403  3495  3295  3337  4151  3360  3335  3482
  4637  3324  3199  3292  4291  3238  3258  4588  3268  3374  3213  3225
  3211  3450  4192  3154  3147  3134  3359  3185  3120  3253  3600  4099
  3169  3122  3157  3294  4139  3045  3025  3210  6006  3006  3028  3180
  3061  3212  3011  3168  3110  3364  3052  3343  4217  3609  3674  3331
  2995  3215  3001  3029  4261  3913  2980  3781  2949  2959  8066  3125
  3174  2977  2898  3242  2888  3010  2857  3282  3726  3175  2883  2851
  2976  2902  2942  3074  3139  2892  2829  2950  2996  3097  3037  4180
  2870  2920  3096  3063  3578  3065  4186  3022  2817  2803  2820  2785
  3369  2856  2772  2753  3014  2936  2983  2819  2896  2961  2758  2793
  3155  2894  2832  2822  3178  3563  3005  3470  2858  4114  2703  2969
  2766  3082  5291  2765  2636  2871  2800  2654  2643  2698  2674  2699
  2804  2690  2662  2906  3150  2939  2957  2733  2764  2799  2971  3273
  2702  2601  2688  2685  2642  2670  2588  2713  2792  2616  2615  2557
  2635  2705  2844  3113  3366  3277  2825  2812  2853  2716  3302  2860
  2748  3684  3161  3044  2989  2771  3141  6221 10381]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 10
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_episodes_v2)

El dataset cuenta con una estructura limpia y un 0% de valores nulos. Asimismo, se determinó que los registros repetidos en los títulos no constituyen fallos de duplicación reales, sino que corresponden a episodios dobles divididos en dos partes independientes con sus propias métricas de rendimiento. Por último, de cara a las próximas fases del proyecto, se contempla la posibilidad de modificar el nombre de las columnas para estandarizar el formato y facilitar su manipulación en el código.

#### 5. Dataset: friends_episodes_v3

El dataset presenta una estructura de variables temporales, descriptivas y de rendimiento técnico de los capítulos de la serie, manteniendo la misma distribución que la versión v2.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_epiv3)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year_of_prod    236 non-null    int64
 1   Season          236 non-null    int64
 2   Episode Number  236 non-null    int64
 3   Episode_Title   236 non-null    str
 4   Duration        236 non-null    int64
 5   Summary         236 non-null    str
 6   Director        236 non-null    str
 7   Stars           236 non-null    float64
 8   Votes           236 non-null    int64
dtypes: float64(1), int64(5), str(3)
memory usage: 16.7 KB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

,count,unique,top,freq
Episode_Title,236,232,The One with Ross's Wedding,2
Summary,236,236,"Monica and the gang introduce Rachel to the ""r...",1
Director,236,28,Kevin Bright,54

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

,count,mean,std,min,25%,50%,75%,max
Year_of_prod,236.0,1998.96,2.84,1994.0,1997.00,1999.0,2001.0,2004.0
Season,236.0,5.38,2.81,1.0,3.00,5.0,8.0,10.0
Episode Number,236.0,12.38,6.94,1.0,6.00,12.0,18.0,25.0
Duration,236.0,22.34,1.51,22.0,22.00,22.0,22.0,30.0
Stars,236.0,8.46,0.40,7.2,8.20,8.4,8.7,9.7
Votes,236.0,3369.61,864.43,2557.0,2886.75,3148.5,3583.5,10381.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
236 filas
9 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Year_of_prod,Season,Episode Number,Episode_Title,Duration,Summary,Director,Stars,Votes
149,2000,7,4,The One with Rachel's Assistant,22,Chaos ensues when Monica and Chandler decide t...,David Schwimmer,8.1,2820
231,2004,10,14,The One with Princess Consuela,22,When Phoebe goes to get her name changed she r...,Gary Halvorson,8.6,2989
24,1995,2,1,The One with Ross's New Girlfriend,22,"Rachel waits for Ross at the airport, unaware ...",Michael Lembeck,8.5,3814
185,2002,8,16,The One Where Joey Tells Rachel,22,Ross freaks out when Joey tells him that he is...,Ben Weiss,8.3,2698
111,1999,5,15,The One with the Girl Who Hits Joey,22,Ross makes enemies out of his new neighbors. C...,Kevin Bright,8.5,3125

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_epiv3)

Columna: Year_of_prod
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 225
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 226
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Episode Number
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 211
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Episode_Title
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['The One Where Monica Gets a Roommate: The Pilot',
            'The One with the Sonogram at the End',
                          'The One with the Thumb',
              'The One with George Stephanopoulos',
  'The One with the East German Laundry Detergent',
                           'The One with the Butt',
                       'The One with the Blackout',
                   'The One Where Nana Dies Twice',
                'The One Where Underdog Gets Away',
                         'The One with the Monkey',
 ...
                   'The One with the Birth Mother',
              'The One Where Chandler Gets Caught',
                'The One Where the Stripper Cries',
                   'The One with Phoebe's Wedding',
                'The One Where Joey Speaks French',
                  'The One with Princess Consuela',
                      'The One Where Estelle Dies',
          'The One with Rachel's Going Away Party',
                            'The Last One: Part 1',
                            'The Last One: Part 2']
Length: 232, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 4
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Duration
 ----------------------------------------------------------------------------------------------------
Valores unicos: [22 30 24 27 26 23]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 230
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Summary
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                                                                                                                    'Monica and the gang introduce Rachel to the "real world" after she leaves her fiancé at the altar.',
                                                                                'Ross finds out his ex-wife is pregnant. Rachel returns her engagement ring to Barry. Monica becomes stressed when her and Ross's parents come to visit.',
                                                  'Monica becomes irritated when everyone likes her new boyfriend more than she does. Chandler resumes his smoking habit. Phoebe is given $7000 when she finds a thumb in a can of soda.',
                                  'Joey and Chandler take Ross to a hockey game to take his mind off the anniversary of the first time he slept with Carol, while the girls become depressed when they realize they don't have a 'plan'.',
           'Eager to spend time with Rachel, Ross pretends his washroom is rat-infested so he can join her at the laundromat. Meanwhile, Joey has Monica pose as his girlfriend, and Chandler struggles to break up with his girlfriend.',
                     'Monica's obsessiveness is put to the test after Rachel cleans the apartment. Joey lands a film role as Al Pacino's butt double. Chandler enjoys a relationship with all of the fun but none of the responsibility.',
                                                                                          'When New York suffers from a blackout, Ross tries to tell Rachel that he likes her, and Chandler gets stuck in an ATM vestibule with a model.',
                                                                                                                          'Monica and Ross mourn the loss of their grandmother. Chandler is shocked to find that people think he is gay.',
                                                                                                                                  'The gang's plans for Thanksgiving go awry after they get locked out of Monica and Rachel's apartment.',
                                                           'The gang make (and break) a pact not to bring dates to their New Years Eve party. Phoebe starts dating a scientist. Ross compensates for his loneliness by getting a monkey.',
 ...
   'After Rachel confirms Joey is more mature in relationships, Phoebe presents him to another friend as date, Sarah, who fails alas to respect his primordial rule by touching food in his plate...                See full summaryÂ Â»',
        'Chandler and Monica have decided they want to raise their offspring in a suburban house and even find a perfect one in Westchester. Rachel and Phoebe see Chandler enter a car with his ...                See full summaryÂ Â»',
                                                    'Old secrets come to light when Ross and Chandler attend a college reunion. Monica and Rachel throw Phoebe a bachelorette party. Joey appears as a celebrity partner on a game show.',
                                                                                                                                                                                'Chaos ensues as Phoebe and Mike prepare to get married.',
                                                                                                  'Phoebe tries to teach Joey to speak French for an audition; Ross and Rachel head out to Long Island after her dad has a heart attack.',
    'When Phoebe goes to get her name changed she realizes she can change it to anything she wants, so she changes it to Princess Consuela Banana Hammock, to Mike's displeasure. Chandler finds ...                See full summaryÂ Â»',
                                                                                              'Ross tries to get Rachel to go back to Ralph Lauren, Joey doesn't know that his agent has died, and Monica and Chandler bump into Janice.',
                                                                                                                                       'The gang throws Rachel a goodbye party, during which she says goodbye to everybody individually.',
   'Erica gives birth to the baby that Monica and Chandler are adopting. However, there's one small added surprise. Meanwhile, Ross and Rachel sleep together one last time before Rachel leaves ...                See full summaryÂ Â»',
 'Phoebe races Ross to the airport in a bid to stop Rachel from leaving for Paris. Monica and Chandler pack up their apartment ahead of their move to their new house, and Joey buys Chandler a new chick and duck as a leaving present.']
Length: 236, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Director
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[       'James Burrows',        'Pamela Fryman',       'Arlene Sanford',
         'Peter Bonerz',         'Paul Lazarus',         'Alan Myerson',
      'Michael Lembeck',         'Gail Mancuso',         'Robby Benson',
         'Kevin Bright',     'Ellen Gittelsohn',       'Mary Kay Place',
      'Thomas Schlamme',      'Steve Zuckerman',         'Terry Hughes',
            'Sam Simon',       'Shelley Jensen',       'Gary Halvorson',
      'David Steinberg', 'Dana De Vally Piazza',        'Joe Regalbuto',
          'Andrew Tsao',         'Todd Holland',      'David Schwimmer',
            'Ben Weiss',        'Stephen Prime',         'Sheldon Epps',
   'Roger Christiansen']
Length: 28, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 208
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Stars
 ----------------------------------------------------------------------------------------------------
Valores unicos: [8.3 8.1 8.2 8.5 9.  8.7 8.8 7.9 8.9 8.4 8.  8.6 9.4 9.1 9.5 7.2 9.2 9.7
 7.4 9.3 7.5 7.8]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 214
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: Votes
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 7440  4888  4605  4468  4438  4274  5469  4156  4038  4064  3996  3926
  4172  3866  3915  3834  3883  4340  3734  3736  3769  3720  3919  4187
  3814  3669  3676  3555  3550  3822  4319  3581  3444  3591  3524  3723
  3864  5736  3928  3435  3407  3403  3495  3295  3337  4151  3360  3335
  3482  4637  3324  3199  3292  4291  3238  3258  4588  3268  3374  3213
  3225  3211  3450  4192  3154  3147  3134  3359  3185  3120  3253  3600
  4099  3169  3122  3157  3294  4139  3045  3025  3210  6006  3006  3028
  3180  3061  3212  3011  3168  3110  3364  3052  3343  4217  3609  3674
  3331  2995  3215  3001  3029  4261  3913  2980  3781  2949  2959  8066
  3125  3174  2977  2898  3242  2888  3010  2857  3282  3726  3175  2883
  2851  2976  2902  2942  3074  3139  2892  2829  2950  2996  3097  3037
  4180  2870  2920  3096  3063  3578  3065  4186  3022  2817  2803  2820
  2785  3369  2856  2772  2753  3014  2936  2983  2819  2896  2961  2758
  2793  3155  2894  2832  2822  3178  3563  3005  3470  2858  4114  2703
  2969  2766  3082  5291  2765  2636  2871  2800  2654  2643  2698  2674
  2699  2804  2690  2662  2906  3150  2939  2957  2733  2764  2799  2971
  3273  2702  2601  2688  2685  2642  2670  2588  2713  2792  2616  2615
  2557  2635  2705  2844  3113  3366  3277  2825  2812  2853  2716  3302
  2860  2748  3684  3161  3044  2989  2771  3141  6221 10381]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 10
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_episodes_v3)

El dataset presenta una estructura completamente limpia y libre de valores nulos, donde las redundancias identificadas en los títulos resultan normales al corresponder a episodios dobles divididos por partes. No obstante, debido a la existencia de columnas repetidas y a la necesidad de estandarizar las etiquetas de las variables, se contempla como acción clave la modificación y alineación de las estructuras de las versiones v2 o v3 para consolidar una base de datos definitiva y optimizada para el análisis.

#### 6. Dataset: friends_escenarios

Este dataset recopila la distribución y el peso visual de las locaciones principales donde se desarrolla la trama de la serie.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_escenarios)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Escenario                8 non-null      str
 1   Tipo                     8 non-null      str
 2   Porcentaje_Escenas_Real  8 non-null      int64
 3   Descripcion              8 non-null      str
 4   Numero_Escenas_Est       8 non-null      int64
dtypes: int64(2), str(3)
memory usage: 452.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

,count,unique,top,freq
Escenario,8,8,Apartamento de Monica,1
Tipo,8,5,Principal,3
Descripcion,8,8,El escenario con más tiempo de pantalla (cocin...,1

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

,count,mean,std,min,25%,50%,75%,max
Porcentaje_Escenas_Real,8.0,12.5,13.01,2.0,3.75,5.5,19.5,38.0
Numero_Escenas_Est,8.0,625.0,650.27,100.0,187.50,275.0,975.0,1900.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
8 filas
5 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Escenario,Tipo,Porcentaje_Escenas_Real,Descripcion,Numero_Escenas_Est
2,Apartamento de Joey,Principal,18,El apartamento frente al de Monica.,900
7,Exteriores / Otros,Especial,2,"Escenas en la calle, taxis, y viajes (Londres,...",100
3,Pasillo (Hallway),Transición,5,Escenas de transición entre los dos apartament...,250
6,Oficina/Trabajos,Trabajo,3,"Museo de Ross, oficina de Chandler, Ralph Laur...",150
4,Apartamento de Ross,Secundario,6,"Incluye su apartamento de soltero y el de ""Ugl...",300

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_escenarios)

Columna: Escenario
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Apartamento de Monica',          'Central Perk',   'Apartamento de Joey',
     'Pasillo (Hallway)',   'Apartamento de Ross', 'Apartamento de Phoebe',
      'Oficina/Trabajos',    'Exteriores / Otros']
Length: 8, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Tipo
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Principal', 'Transición', 'Secundario', 'Trabajo', 'Especial']
Length: 5, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 3
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Porcentaje_Escenas_Real
 ----------------------------------------------------------------------------------------------------
Valores unicos: [38 24 18  5  6  4  3  2]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Descripcion
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['El escenario con más tiempo de pantalla (cocina y salón de Monica).',
               'El punto de encuentro social, segundo en importancia.',
                                 'El apartamento frente al de Monica.',
       'Escenas de transición entre los dos apartamentos principales.',
         'Incluye su apartamento de soltero y el de "Ugly Naked Guy".',
                   'Aparece menos debido a que Phoebe vive más lejos.',
              'Museo de Ross, oficina de Chandler, Ralph Lauren, etc.',
              'Escenas en la calle, taxis, y viajes (Londres, Vegas).']
Length: 8, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Numero_Escenas_Est
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1900 1200  900  250  300  200  150  100]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_escenarios)

El dataset presenta una estructura completamente limpia y un 0% de valores nulos, identificándose que las redundancias en los registros son normales debido a la naturaleza de los datos recopilados. De cara a las próximas fases del proyecto, se plantea llevar a cabo una reestructuración técnica que incluye la modificación y estandarización de los nombres de las columnas, así como la posible eliminación de la variable Tipo, al determinarse que no aporta valor relevante ni impacto significativo para los objetivos del análisis.

#### 7. Dataset: friends_info

Este archivo es una base de datos detallada sobre la emisión original de la serie y su impacto en la audiencia televisiva.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_info)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season             236 non-null    int64
 1   episode            236 non-null    int64
 2   title              236 non-null    str
 3   directed_by        236 non-null    str
 4   written_by         236 non-null    str
 5   air_date           236 non-null    str
 6   us_views_millions  236 non-null    float64
 7   imdb_rating        236 non-null    float64
dtypes: float64(2), int64(2), str(4)
memory usage: 14.9 KB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

            count unique                          top freq
title         236    227  The One After the Superbowl    2
directed_by   236     30               Gary Halvorson   54
written_by    236    102                  Alexa Junge   11
air_date      236    225                   1995-02-23    2

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

                   count   mean   std    min   25%    50%    75%   max
season             236.0   5.38  2.81   1.00   3.0   5.00   8.00  10.0
episode            236.0  12.38  6.94   1.00   6.0  12.00  18.00  25.0
us_views_millions  236.0  25.37  5.23  15.65  22.3  24.48  27.72  52.9
imdb_rating        236.0   8.46  0.40   7.20   8.2   8.40   8.70   9.7

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
236 filas
8 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,season,episode,title,directed_by,written_by,air_date,us_views_millions,imdb_rating
219,10,2,The One Where Ross Is Fine,Ben Weiss,Sherry Bilsing-Graham & Ellen Plummer,2003-10-02,22.38,8.8
217,9,24,The One in Barbados,Kevin S. Bright,Shana Goldberg-Meehan & Scott SilveriMarta Kau...,2003-05-15,25.46,8.7
57,3,10,The One Where Rachel Quits,Terry Hughes,Gregory S. Malins & Michael Curtis,1996-12-12,25.10,8.1
52,3,5,The One with Frank Jr.,Steve Zuckerman,Shana Goldberg-Meehan & Scott Silveri,1996-10-17,23.30,8.1
73,4,1,The One with the Jellyfish,Shelley Jensen,Wil Calhoun,1997-09-25,29.40,9.1

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_info)

Columna: season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 226
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: episode
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 211
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: title
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                     'The Pilot',
           'The One with the Sonogram at the End',
                         'The One with the Thumb',
             'The One with George Stephanopoulos',
 'The One with the East German Laundry Detergent',
                          'The One with the Butt',
                      'The One with the Blackout',
                  'The One Where Nana Dies Twice',
               'The One Where Underdog Gets Away',
                        'The One with the Monkey',
 ...
             'The One with the Late Thanksgiving',
                  'The One with the Birth Mother',
             'The One Where Chandler Gets Caught',
               'The One Where the Stripper Cries',
                  'The One with Phoebe's Wedding',
               'The One Where Joey Speaks French',
                 'The One with Princess Consuela',
                     'The One Where Estelle Dies',
         'The One with Rachel's Going Away Party',
                                   'The Last One']
Length: 227, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 9
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: directed_by
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                   'James Burrows',                    'Pamela Fryman',
                   'Arlene Sanford',                     'Peter Bonerz',
                     'Paul Lazarus',                     'Alan Myerson',
                  'Michael Lembeck',                     'Gail Mancuso',
                     'Robby Benson',                  'Kevin S. Bright',
                 'Ellen Gittelsohn',                   'Mary Kay Place',
                  'Thomas Schlamme',                  'Steve Zuckerman',
                     'Terry Hughes',                        'Sam Simon',
                   'Shelley Jensen',                   'Gary Halvorson',
                  'David Steinberg',              'Dana DeVally Piazza',
             'Dana DeValley Piazza',                    'Joe Regalbuto',
                      'Andrew Tsao',                     'Todd Holland',
                  'David Schwimmer',                        'Ben Weiss',
                    'Stephen Prime', 'Kevin S. Bright & Gary Halvorson',
                     'Sheldon Epps',               'Roger Christiansen']
Length: 30, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 206
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: written_by
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                                                 'David Crane & Marta Kauffman',
                                                                'Jeffrey Astrof & Mike Sikowitz',
                                                                                   'Alexa Junge',
                                                                'Jeff Greenstein & Jeff Strauss',
                                                                  'Adam Chase & Ira Ungerleider',
                                                                  'Marta Kauffman & David Crane',
                                 'Jeffrey Astrof & Mike Sikowitz & Adam Chase & Ira Ungerleider',
                                                                                 'Bill Lawrence',
                                                                                   'Doty Abrams',
           'Story by : David Crane & Marta KauffmanTeleplay by : Jeff Greenstein & Jeff Strauss',
 ...
                                                                                 'Peter Tibbals',
 'Story by : Brian Buckner & Sebastian JonesTeleplay by : Sherry Bilsing-Graham & Ellen Plummer',
                                        'Story by : Dana Klein BorkowTeleplay by : Mark Kunerth',
                                          'Story by : Scott SilveriTeleplay by : Robert Carlock',
                             'Shana Goldberg-Meehan & Scott SilveriMarta Kauffman & David Crane',
                                                                                 'Brian Buckner',
                                                                               'Sebastian Jones',
                                                            'Robert Carlock & Dana Klein Borkow',
                                           'Story by : Robert CarlockTeleplay by : Tracy Reilly',
                             'Story by : Mark KunerthTeleplay by : David Crane & Marta Kauffman']
Length: 102, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 134
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: air_date
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['1994-09-22', '1994-09-29', '1994-10-06', '1994-10-13', '1994-10-20',
 '1994-10-27', '1994-11-03', '1994-11-10', '1994-11-17', '1994-12-15',
 ...
 '2003-11-20', '2004-01-08', '2004-01-15', '2004-02-05', '2004-02-12',
 '2004-02-19', '2004-02-26', '2004-04-22', '2004-04-29', '2004-05-06']
Length: 225, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 11
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: us_views_millions
 ----------------------------------------------------------------------------------------------------
Valores unicos: [21.5  20.2  19.5  19.7  18.6  18.2  23.5  21.1  23.1  19.9  26.6  24.
 25.8  23.8  24.8  26.1  30.5  30.4  29.4  30.   28.4  29.9  28.7  31.3
 32.1  29.8  30.2  28.1  28.3  32.9  27.8  32.2  31.6  52.9  33.6  31.1
 30.1  31.2  27.4  24.7  25.5  29.   26.8  26.7  25.2  23.3  29.3  25.1
 29.6  28.   28.9  27.3  23.7  24.4  23.2  22.6  24.2  28.8  24.3  25.7
 26.4  23.9  27.1  25.3  21.7  21.8  21.9  25.4  24.1  25.9  25.   23.
 27.   24.9  27.7  26.   24.5  20.9  19.6  21.3  22.9  21.6  22.4  23.6
 22.7  22.1  19.2  22.3  20.7  20.5  18.8  20.6  20.   30.7  25.54 27.93
 22.66 24.43 22.01 23.73 16.57 21.08 23.26 24.37 22.86 22.24 21.75 21.22
 20.84 17.81 16.55 16.3  15.65 17.23 30.05 31.7  30.04 29.2  25.58 25.64
 26.96 24.24 26.54 22.44 23.85 25.53 29.24 28.64 27.52 26.3  22.05 22.59
 23.97 24.32 34.91 34.01 28.93 26.63 25.82 24.46 27.51 25.35 26.76 25.43
 22.29 23.67 23.66 23.37 20.85 19.52 21.   20.79 18.25 20.71 19.03 19.55
 25.46 24.54 22.38 21.87 18.77 19.37 20.38 20.21 20.66 25.49 26.68 24.91
 24.27 22.83 22.64 24.51 52.46]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 63
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: imdb_rating
 ----------------------------------------------------------------------------------------------------
Valores unicos: [8.3 8.1 8.2 8.5 9.  8.7 8.8 7.9 8.9 8.4 8.  8.6 9.4 9.1 9.5 7.2 9.2 9.7
 7.4 9.3 7.5 7.8]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 214
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_info)

El dataset presenta un estado de limpieza óptimo al registrar un 0% de valores nulos, identificándose además que las repeticiones en la columna de títulos son completamente normales al corresponder a episodios dobles divididos por partes. No obstante, de cara a las próximas fases de transformación, se detecta la necesidad de realizar una limpieza exhaustiva en la columna de guionistas (written_by), dado que presenta inconsistencias debidas a la mención de múltiples autores o al uso de términos variantes como "story by", requiriendo una estrategia de estandarización para optimizar su posterior análisis.

#### 8. Dataset: friends_quotes

Este archivo funciona como un registro textual de los diálogos y guiones hablados por los personajes a lo largo de toda la serie.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_quotes)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 60291 entries, 0 to 60290
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   author          60291 non-null  str
 1   episode_number  60291 non-null  float64
 2   episode_title   60291 non-null  str
 3   quote           60291 non-null  str
 4   quote_order     60291 non-null  float64
 5   season          60291 non-null  float64
dtypes: float64(3), str(3)
memory usage: 2.8 MB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

               count unique          top  freq
author         60291   1024       Rachel  8318
episode_title  60291    226  In Barbados   597
quote          60291  52312        What?   481

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

                  count    mean    std  min   25%    50%    75%    max
episode_number  60291.0   12.42   6.92  1.0   6.0   12.0   18.0   25.0
quote_order     60291.0  141.20  93.53  0.0  67.0  134.0  202.0  597.0
season          60291.0    5.48   2.82  1.0   3.0    6.0    8.0   10.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
60291 filas
6 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,author,episode_number,episode_title,quote,quote_order,season
23102,Rachel,21.0,The Invitation,I could not have done this without you.,72.0,4.0
21597,Chandler,15.0,All The Rugby,"Well, I-I thought I did but, I-I guess I did not!",101.0,4.0
36406,Monica,1.0,Monica's Thunder,"Awww, come onwaitstop it. Okay, to Monica.",19.0,7.0
4784,Barry,20.0,The Evil Orthodontist,"No, it was. It was very very good.",66.0,1.0
1654,Phoebe,7.0,The Blackout,Wait a minute. What's his name?,148.0,1.0

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_quotes)

Columna: author
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                          'Monica',                             'Joey',
                         'Chandler',                           'Phoebe',
                              'All',                             'Ross',
                           'Rachel',                         'Waitress',
 'Phoebe, Ross, Chandler, and Joey',                             'Paul',
 ...
                  'Phoebe and Joey',          'Jennifer Aniston (V.O.)',
             'Phoebe, Ross, Rachel',                'Gate attendant #1',
                     'Ticket agent',                     'Passenger #1',
                   'Air stewardess',                     'Passenger #2',
                     'Passenger #3',                'Gate attendant #2']
Length: 1024, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 59267
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: episode_number
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 60266
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: episode_title
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[           'Monica Gets A Roommate',           'The Sonogram At The End',
                         'The Thumb',             'George Stephanopoulos',
 'The East German Laundry Detergent',                          'The Butt',
                      'The Blackout',                   'Nana Dies Twice',
                'Underdog Gets Away',                        'The Monkey',
 ...
             'The Late Thanksgiving',                  'The Birth Mother',
              'Chandler Gets Caught',                'The Stripper Cries',
                  'Phoebe's Wedding',                'Joey Speaks French',
                 'Princess Consuela',                      'Estelle Dies',
         'Rachel's Going Away Party',         'The Last One, Part I & II']
Length: 226, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 60065
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: quote
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                                               'There's nothing to tell! He's just some guy I work with!',
                                        'C'mon, you're going out with the guy! There's gotta be something wrong with him!',
                                                'All right Joey, be nice. So does he have a hump? A hump and a hairpiece?',
                                                                                                'Wait, does he eat chalk?',
                                         'Just, 'cause, I don't want her to go through what I went through with Carl- oh!',
           'Okay, everybody relax. This is not even a date. It's just two people going out to dinner and- not having sex.',
                                                                                               'Sounds like a date to me.',
     'Alright, so I'm back in high school, I'm standing in the middle of the cafeteria, and I realize I am totally naked.',
                                                                                               'Oh, yeah. Had that dream.',
                                                               'Then I look down, and I realize there's a phone... there.',
 ...
 'Wait a minute. What about that summer during college that you lived with grandma, and you tried to make it as a dancer?',
                                                      'Do you realise we almost made it ten years without that coming up?',
                                                       'Oh, honey, I forgot. I promised Treeger that we'd leave our keys.',
                                                                                                       'Yeah. I guess so.',
                                                                     '(crying) This is harder than I thought it would be.',
                                                                                                 'Oh, it's gonna be okay.',
                                  '(crying) Do you guys have to go to the new house right away, or do you have some time?',
                                                                                                       'We got some time.',
                                                                                        'Okay, should we get some coffee?',
                                                                                                            'Sure. Where?']
Length: 52312, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 7979
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: quote_order
 ----------------------------------------------------------------------------------------------------
Valores unicos: [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 168. 169.
 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182. 183.
 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196. 197.
 198. 199. 200. 201. 202. 203. 204. 205. 206. 207. 208. 209. 210. 211.
 212. 213. 214. 215. 216. 217. 218. 219. 220. 221. 222. 223. 224. 225.
 226. 227. 228. 229. 230. 231. 232. 233. 234. 235. 236. 237. 238. 239.
 240. 241. 242. 243. 244. 245. 246. 247. 248. 249. 250. 251. 252. 253.
 254. 255. 256. 257. 258. 259. 260. 261. 262. 263. 264. 265. 266. 267.
 268. 269. 270. 271. 272. 273. 274. 275. 276. 277. 278. 279. 280. 281.
 282. 283. 285. 286. 287. 288. 289. 290. 291. 292. 293. 294. 295. 296.
 297. 298. 299. 300. 301. 302. 108. 167. 284. 303. 304. 305. 306. 307.
 308. 309. 310. 311. 312. 313. 314. 315. 316. 317. 318. 319. 320. 321.
 322. 323. 324. 325. 326. 327. 328. 329. 330. 331. 332. 333. 334. 335.
 336. 337. 338. 339. 340. 341. 342. 343. 344. 345. 346. 347. 348. 349.
 350. 351. 352. 353. 354. 355. 356. 357. 358. 359. 360. 361. 362. 363.
 364. 365. 366. 367. 368. 369. 370. 371. 372. 373. 374. 375. 376. 377.
 378. 379. 380. 381. 382. 383. 384. 385. 386. 387. 388. 389. 390. 391.
 392. 393. 394. 395. 396. 397. 398. 399. 400. 401. 402. 403. 404. 405.
 406. 407. 408. 409. 410. 411. 412. 413. 414. 415. 416. 417. 418. 419.
 420. 421. 422. 423. 424. 425. 426. 427. 428. 429. 430. 431. 432. 433.
 434. 435. 436. 437. 438. 439. 440. 441. 442. 443. 444. 445. 446. 447.
 449. 450. 451. 452. 453. 454. 455. 456. 457. 458. 448. 459. 460. 461.
 462. 463. 464. 465. 466. 467. 468. 469. 470. 471. 472. 473. 474. 475.
 476. 477. 478. 479. 480. 481. 482. 483. 484. 485. 486. 487. 488. 489.
 490. 491. 492. 493. 494. 495. 496. 497. 498. 499. 500. 501. 502. 503.
 504. 505. 506. 507. 508. 509. 510. 511. 512. 513. 514. 515. 516. 517.
 518. 519. 520. 521. 522. 523. 524. 525. 526. 527. 528. 529. 530. 531.
 532. 533. 534. 535. 536. 537. 538. 539. 540. 541. 542. 544. 545. 546.
 543. 547. 548. 549. 550. 551. 552. 553. 554. 555. 556. 557. 558. 559.
 560. 561. 562. 563. 564. 565. 566. 567. 568. 569. 570. 571. 572. 573.
 574. 575. 576. 577. 578. 579. 580. 581. 582. 583. 584. 585. 586. 587.
 588. 589. 590. 591. 592. 593. 594. 595. 596. 597.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 59693
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 60281
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends_quotes)

El dataset registra un 0% de valores nulos e incluye registros duplicados que se consideran normales, ya que corresponden a múltiples líneas de diálogo de un mismo capítulo y personaje, lo que genera la repetición natural de títulos y nombres. Como acción de mejora, se plantea transformar las variables numéricas de float a entero (int) para optimizar la estructura del archivo sin alterar el análisis.

#### 9. Dataset: friends

Este archivo funciona como un registro cronológico y estructurado de los libretos, diálogos y anotaciones de escena de la serie.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_friends)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 67373 entries, 0 to 67372
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       67373 non-null  str
 1   speaker    67097 non-null  str
 2   season     67373 non-null  int64
 3   episode    67373 non-null  int64
 4   scene      67373 non-null  int64
 5   utterance  67373 non-null  int64
dtypes: int64(4), str(2)
memory usage: 3.1 MB
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

         count unique           top  freq
text     67373  56920          Hey!   661
speaker  67097    699  Rachel Green  9312

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

             count   mean    std  min  25%   50%   75%    max
season     67373.0   5.44   2.79  1.0  3.0   5.0   8.0   10.0
episode    67373.0  12.61   6.96  1.0  7.0  13.0  19.0   25.0
scene      67373.0   6.86   4.29  1.0  3.0   6.0  10.0   29.0
utterance  67373.0  18.08  21.15  0.0  6.0  12.0  22.0  255.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
67373 filas
6 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,text,speaker,season,episode,scene,utterance
14655,"Oh, it's just like a bloodbath in here today.",Rachel Green,3,8,4,31
47788,Oh my God!,Rachel Green,7,22,15,19
20102,"Hey, you guys! What do you, what do you think ...",Ross Geller,4,1,10,10
52293,"Potato, potaato.",Phoebe Buffay,8,14,3,33
53634,[Cut to the interview.],Scene Directions,8,19,6,7

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_friends)

Columna: text
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                                               'There's nothing to tell! He's just some guy I work with!',
                                        'C'mon, you're going out with the guy! There's gotta be something wrong with him!',
                                                'All right Joey, be nice. So does he have a hump? A hump and a hairpiece?',
                                                                                                'Wait, does he eat chalk?',
                                                                                              '(They all stare, bemused.)',
                                         'Just, 'cause, I don't want her to go through what I went through with Carl- oh!',
           'Okay, everybody relax. This is not even a date. It's just two people going out to dinner and- not having sex.',
                                                                                               'Sounds like a date to me.',
                                                                                                            '[Time Lapse]',
     'Alright, so I'm back in high school, I'm standing in the middle of the cafeteria, and I realize I am totally naked.',
 ...
 'Wait a minute. What about that summer during college that you lived with grandma, and you tried to make it as a dancer?',
                                                      'Do you realise we almost made it ten years without that coming up?',
                                                       'Oh, honey, I forgot. I promised Treeger that we'd leave our keys.',
                                                                                                       'Yeah. I guess so.',
                                                                              'This is harder than I thought it would be.',
                                                                                                 'Oh, it's gonna be okay.',
                                           'Do you guys have to go to the new house right away, or do you have some time?',
                                                                                                       'We got some time.',
                                                                                        'Okay, should we get some coffee?',
                                                                                                            'Sure. Where?']
Length: 56920, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 10453
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: speaker
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[    'Monica Geller',    'Joey Tribbiani',     'Chandler Bing',
     'Phoebe Buffay',  'Scene Directions',             '#ALL#',
       'Ross Geller',      'Rachel Green',          'Waitress',
                 nan,
 ...
         'Mackenzie',              'Rita',              'Lady',
  'Jennifer Aniston', 'Gate Attendant #1',      'Passenger #1',
    'Air Stewardess',      'Passenger #2',      'Passenger #3',
 'Gate Attendant #2']
Length: 700, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 66673
 ----------------------------------------------------------------------------------------------------
Valores nulos: 276
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: season
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 67363
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: episode
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 67348
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: scene
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 67344
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: utterance
 ----------------------------------------------------------------------------------------------------
Valores unicos: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174   0 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 67117
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (friends)

El dataset demuestra una sólida consistencia al presentarse prácticamente limpio y registrar un 0% de valores nulos, con la única excepción de la columna speaker, donde las ausencias resultan normales debido a efectos de sonido, reacciones corporales o voces de fondo provenientes de fuentes no registradas. Asimismo, las duplicidades observadas en los registros se consideran habituales e inherentes al contexto de los datos, ya que corresponden a la repetición natural de las variables de ubicación cronológica por cada una de las intervenciones y diálogos que componen el guion de la serie.

#### 10. Dataset: phoebe_buffay_songs_v2

Este archivo funciona como un registro temático y detallado de las composiciones musicales interpretadas por el personaje de Phoebe Buffay a lo largo de la serie.

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_songs)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temporada    21 non-null     int64
 1   Episodio     21 non-null     str
 2   Cancion      21 non-null     str
 3   Descripcion  21 non-null     str
dtypes: int64(1), str(3)
memory usage: 804.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

            count unique                                  top freq
Episodio       21     18                                 2x06    2
Cancion        21     21                            Your Love    1
Descripcion    21     21  Your love is like a giant pigeon...    1

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

           count  mean   std  min  25%  50%  75%   max
Temporada   21.0  4.19  2.82  1.0  2.0  3.0  6.0  10.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
21 filas
4 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Temporada,Episodio,Cancion,Descripcion
7,2,2x12,Sexual Freedom,The cow in the meadow goes moo...
4,2,2x06,Terry's a Jerk,Terry's a jerk and he won't let me work!
12,4,4x10,The Holiday Song,"Monica, Monica, have a happy Hanukkah!"
3,2,2x06,Smelly Cat,Su mayor éxito. What are they feeding you?
2,1,1x23,Babies,They're tiny and chubby and so sweet to touch.

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_songs)

Columna: Temporada
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  2  3  4  5  6  7  9 10]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 12
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Episodio
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[ '1x01',  '1x10',  '1x23',  '2x06',  '2x08',  '2x12',  '3x08',  '3x14',
  '4x05',  '4x10',  '5x10',  '5x13',  '6x07',  '7x15',  '7x19',  '9x07',
  '9x13', '10x07']
Length: 18, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 3
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Cancion
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                  'Your Love',                     'Snowman',
                      'Babies',                  'Smelly Cat',
              'Terry's a Jerk',          'Two of Them Kissed',
        'The Grandmother Song',              'Sexual Freedom',
                'Endless Love',                'Sticky Shoes',
                'Jingle Bitch', 'The 66 Colors of my Bedroom',
            'The Holiday Song',      'The Girl Who Hits Joey',
             'The Phoebe Song',                'Running Song',
              'The Geller Cup',             'The Shower Song',
     'Baby Got Back (Lullaby)',              'Emma's Lullaby',
            'The Wedding Song']
Length: 21, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Descripcion
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                            'Your love is like a giant pigeon...',
 'How was I supposed to know that my mom was dead in the kitchen?',
                  'They're tiny and chubby and so sweet to touch.',
                      'Su mayor éxito. What are they feeding you?',
                        'Terry's a jerk and he won't let me work!',
                   'Resumen del drama entre Ross, Rachel y Julie.',
                    'Now grandma's a person who everyone likes...',
                               'The cow in the meadow goes moo...',
                                               'Dúo con Chandler.',
                               'My favorite shoes, so good to me.',
                                   'Jingle bitch screwed me over!',
                                  'Canción interrumpida por Joey.',
                          'Monica, Monica, have a happy Hanukkah!',
                                'Sobre la novia violenta de Joey.',
                                                  'P-H-O-E-B-E...',
                'And the crusty old man said 'I'll do what I can'',
                                       'Mención a la copa Geller.',
                       'I'm in the shower and I'm writing a song.',
                                   'Versión para Emma con Rachel.',
                 'Sleepy girl, sleepy girl, with the smelly feet.',
              'Intento fallido para la boda de Monica y Chandler.']
Length: 21, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 0
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (phoebe_buffay_songs_v2)

El dataset demuestra una excelente integridad al registrar un 0% de valores nulos, identificándose que las duplicidades en los registros son normales y esperadas debido a que el personaje interpreta múltiples canciones dentro de un mismo episodio. Asimismo, el formato actual de la columna Episodio se valida como definitivo al estar alineado intencionalmente con los requerimientos técnicos de la fase de visualización; no obstante, de cara a la estandarización final de la base de datos, se contempla como acción de mejora la traducción y cambio de los títulos de las columnas al idioma inglés.

#### 11. Dataset: apariciones_detalladas_pato_y_pollito(1)

Este archivo funciona como un registro específico y temático centrado en el seguimiento de las mascotas recurrentes de la serie (el pato y el pollito).

In [ ]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_pato_pollito)

Información sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Temporada  21 non-null     int64
 1   Episodio   21 non-null     str
 2   Animal     21 non-null     str
 3   Accion     21 non-null     str
dtypes: int64(1), str(3)
memory usage: 804.0 bytes
----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cualitativas:

         count unique                                        top freq
Episodio    21     13                                       3x22    2
Animal      21      2                                       Pato   12
Accion      21     14  Aparecen en el apartamento de los chicos.    2

----------------------------------------------------------------------------------------------------
Análisis descriptivo de las variables cuantitativas:

           count  mean   std  min  25%  50%  75%  max
Temporada   21.0  4.19  0.98  3.0  4.0  4.0  5.0  6.0

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
21 filas
4 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Temporada,Episodio,Animal,Accion
15,5,5x02,Pollito,Regresan al apartamento de los chicos.
1,3,3x22,Pollito,Joey y Chandler cuidan de él.
18,6,6x01,Pollito,Aparecen brevemente tras la boda en Las Vegas.
2,3,3x22,Pato,Chandler lo rescata para que el pollito tenga ...
4,3,3x25,Pato,Aparecen en el apartamento de los chicos.

In [ ]:
#Revisión detallada por columna para detectar inconsistencias categóricas, redundancias, cardinalidad de valores únicos y nulos
trans.analisis_columnas(df_pato_pollito)

Columna: Temporada
 ----------------------------------------------------------------------------------------------------
Valores unicos: [3 4 5 6]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 17
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Episodio
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['3x21', '3x22', '3x25', '4x01', '4x02', '4x07', '4x12', '4x17', '4x21',
 '5x02', '5x21', '6x01', '6x20']
Length: 13, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 8
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Animal
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Pollito', 'Pato']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 19
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Accion
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[                                         'Joey lo compra',
                           'Joey y Chandler cuidan de él.',
 'Chandler lo rescata para que el pollito tenga un amigo.',
               'Aparecen en el apartamento de los chicos.',
                              'Escenas en el apartamento.',
               'Se traga el anillo de compromiso de Ross.',
                     'Chandler los castiga en el pasillo.',
      'Se mudan al apartamento de Monica tras la apuesta.',
                'Phoebe cree que es su madre reencarnada.',
     'Joey los cuida mientras los demás están en Londres.',
                  'Regresan al apartamento de los chicos.',
            'Participa en la carrera de pelotas de fuego.',
          'Aparecen brevemente tras la boda en Las Vegas.',
                        'Aparece en una subtrama de Joey.']
Length: 14, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 7
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------

#### Conclusiones (apariciones_detalladas_pato_pollito(1))

El dataset demuestra una óptima integridad al registrar un 0% de valores nulos, identificándose que las repeticiones en las variables son completamente normales y esperadas; esto se debe a que la columna Animal se limita a dos únicos sujetos (el pato y el pollito) y a que la columna Accion describe de forma idéntica el contexto de la escena para ambos cuando interactúan juntos. Asimismo, se valida que el formato de la columna Episodio es el definitivo por responder de manera intencional a los requerimientos técnicos de la fase de visualización, contemplándose como única acción de mejora la traducción y cambio de los nombres de las columnas al idioma inglés.

# Conclusiones finales del EDA

- Calidad de Datos: Integridad excelente con un 0% de nulos en la mayoría de los archivos. La única excepción está en la columna speaker de los guiones, lo cual es normal ya que representa sonidos de fondo, reacciones corporales o voces ambientales no registradas.

- Duplicados: Las repeticiones no son errores; se justifican por la estructura lógica de los datos (episodios dobles, personajes que cantan varias canciones en un mismo capítulo o escenas donde el pato y el pollito interactúan juntos bajo una misma descripción, etc).

- Optimización de Tipos y Limpieza: Se plantea transformar las variables numéricas de orden de float a entero (int) para mejorar la estructura. Asimismo, se detecta la necesidad de limpiar y estandarizar la columna written_by (escrito por) en el dataset de información, debido a la presencia de múltiples autores y variantes de texto como "story by".

- Estandarización y Visualización: Se valida el formato de la columna Episodio (ej. 1x01) por ser idóneo para el diseño de tableros. Como acción final, se propone eliminar columnas no relevantes (como Tipo en escenarios) y traducir los encabezados al inglés para unificar todo el proyecto.

- Los datasets son complementarios y combinables, salvo: apariciones_detalladas_pato_y_pollito(1), bodas_divorcios_de_ross, cameos_friends_completos, friends_escedarios y phoebe_buffay_songs_v2.

Esta fase permite definir claramente los pasos de la siguiente etapa: limpieza y transformación.