# Fase 1 · Análisis Exploratorio de Datos (EDA)

## Objetivo

El objetivo de esta fase es realizar una exploración inicial de los distintos datasets relacionados con la serie de *Friends*, procedentes tanto de fuentes públicas (Kaggle) como de datasets generados y enriquecidos mediante técnicas de IA. Esta revisión permite comprender su estructura, evaluar su calidad y detectar posibles inconsistencias que puedan afectar a las siguientes fases del proyecto.

En esta etapa nos centramos en:

- identificar los datasets disponibles y sus variables principales,
- analizar dimensiones, tipos de datos y coherencia interna,
- detectar valores nulos, duplicados y problemas de calidad,
- explorar variables clave para entender el comportamiento del dataset,
- y anticipar necesidades de limpieza, normalización y transformación.

Este análisis proporciona una base sólida para definir la estrategia de preparación de datos en la fase ETL.

In [3]:
# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación de librerías
import pandas as pd
import numpy as np

# Importación del módulo de transformación personalizado
from src.etl.load_data import load_friends_data_raw
from src.etl import transform as trans

# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

## 1. Carga de los datasets

Se cargan los distintos archivos que contienen información sobre personajes, guiones, temporadas y métricas de diálogo.
Cada uno aporta una dimensión diferente al análisis.

In [4]:
dfs = load_friends_data_raw()

df_bodas_divorcios = dfs["bodas_divorcios"]
df_cameos = dfs["cameos"]
df_emotions = dfs["emotions"]
df_epiv3 = dfs["epiv3"]
df_escenarios = dfs["escenarios"]
df_info = dfs["info"]
df_quotes = dfs["quotes"]
df_friends = dfs["friends"]
df_songs = dfs["songs"]
df_pato_pollito = dfs["pato_pollito"]

[2026-05-22 10:16:30] INFO - Cargando datasets desde: C:\Users\dacil\Desktop\Adalab\pair\modulo_4_pair\friends-analytics-workflow\data_raw
[2026-05-22 10:16:30] INFO - → Cargando bodas_divorcios_ross.csv...
[2026-05-22 10:16:30] INFO - → Cargando cameos_friends_completo.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends_emotions.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends_episodes.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends_escenarios.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends_info.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends_quotes.csv...
[2026-05-22 10:16:30] INFO - → Cargando friends.csv...
[2026-05-22 10:16:30] INFO - → Cargando phoebe_buffay_songs.csv...
[2026-05-22 10:16:30] INFO - → Cargando apariciones_detalladas_pato_y_pollito.csv...
[2026-05-22 10:16:30] INFO - Todos los datasets fueron cargados correctamente.

### Procedemos con la exploración de cada fichero

#### 1. Dataset: Bodas_divorcios_ross
El dataset contiene datos registran el historial de matrimonios y divorcios de los personajes de la serie Friends (haciendo especial honor a los múltiples matrimonios de Ross Geller).

En este bloque se revisará la estructura general del dataset, la presencia de valores nulos, la existencia de duplicados y la variable Personaje, ya que será la variable categórica principal que articulará el análisis del historial de eventos del proyecto.

In [5]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_bodas_divorcios)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 6
- Columnas: 4

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Personaje  6 non-null      str
 1   Evento     6 non-null      str
 2   Temporada  6 non-null      int64
 3   Detalle    6 non-null      str
dtypes: int64(1), str(3)
memory usage: 324.0 bytes

🔹 Nulos:
Personaje    0.0
Evento       0.0
Temporada    0.0
Detalle      0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

          count unique                                    top freq
Personaje     6      3                          Carol Willick    2
Evento        6      2                                   Boda    3
Detalle       6      6  Ocurre antes del piloto (flashbacks).    1

🔹 Descriptivo variables cuantitativas:

           count  mean   std  min   25%  50%  75%  max
Temporada    6.0   3.5  2.43  0.0  1.75  4.5  5.0  6.0

🔹 Muestra del dataframe:

,Personaje,Evento,Temporada,Detalle
0,Carol Willick,Boda,0,Ocurre antes del piloto (flashbacks).
2,Emily Waltham,Boda,4,Boda en Londres; Ross dice el nombre de Rachel.
5,Rachel Green,Divorcio,6,Ross intenta ocultar que no tramitó la anulación.
3,Emily Waltham,Divorcio,5,Emily le pide no ver a Rachel y él no cumple.
1,Carol Willick,Divorcio,1,Ella descubre que es lesbiana.

#### Conclusiones (bodas_divorcios_ross)

El dataset presenta una estructura simple, 100% limpia y libre de valores nulos, donde la redundancia identificada en Personaje y Evento no representa un error ni afecta los resultados, sino que cumple un fin estrictamente informativo y relacional para mapear las transiciones de cada suceso. Posibilidad de cambiar los nombres de las columnas al inglés y en minúculas.

#### 2. Dataset: cameos_friends_completo
Este nuevo archivo (cameos_friends_completo.csv) contiene el registro de las apariciones de actores invitados y celebridades en la serie Friends.

En este bloque se revisará la estructura general del dataset, la presencia de valores nulos y la existencia de duplicados.

In [6]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_cameos)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 25
- Columnas: 3

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Actor/Actriz           25 non-null     str
 1   Personaje              25 non-null     str
 2   Descripción/Temporada  25 non-null     str
dtypes: str(3)
memory usage: 732.0 bytes

🔹 Nulos:
Actor/Actriz             0.0
Personaje                0.0
Descripción/Temporada    0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

,count,unique,top,freq
Actor/Actriz,25,25,Brad Pitt,1
Personaje,25,25,Will Colbert,1
Descripción/Temporada,25,25,Antiguo compañero que odiaba a Rachel (T8),1

🔹 Descriptivo variables cuantitativas:
No hay variables numéricas.

🔹 Muestra del dataframe:

,Actor/Actriz,Personaje,Descripción/Temporada
6,Billy Crystal,Tim,Amigo de Tomas en el Central Perk (T3)
4,Danny DeVito,Roy,El stripper sensible en la despedida de Phoebe...
16,Jean-Claude Van Damme,Él mismo,Actor en la película que rueda Joey (T2)
21,Susan Sarandon,Jessica Lockhart,Actriz de 'Days of Our Lives' (T7)
20,Jeff Goldblum,Leonard Hayes,Director de una obra donde audiciona Joey (T9)

#### Conclusiones (cameos_friends_completo)

El dataset presenta una estructura simple, con un estado de limpieza óptimo al registrar un 0% de valores nulos y cero registros duplicados. No obstante, desde la perspectiva de ingeniería de datos, se identifica la necesidad de aplicar una transformación para disociar la columna Descripción/Temporada en dos atributos independientes, permitiendo así aislar la variable temporal para su correcto análisis cuantitativo.

#### 3. Dataset: friends_emotions

A diferencia de los anteriores, este set de datos está diseñado para realizar análisis agregados complejos, tales como evaluar la evolución del estado emocional de los personajes a lo largo de las temporadas o identificar las escenas con mayor intensidad dramática o cómica. Posibilidad de cambiar los nombres al inglés y en misnúsculas.

In [7]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_emotions)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 12606
- Columnas: 5

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 12606 entries, 0 to 12605
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   season     12606 non-null  int64
 1   episode    12606 non-null  int64
 2   scene      12606 non-null  int64
 3   utterance  12606 non-null  int64
 4   emotion    12606 non-null  str
dtypes: int64(4), str(1)
memory usage: 492.6 KB

🔹 Nulos:
season       0.0
episode      0.0
scene        0.0
utterance    0.0
emotion      0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

         count unique      top  freq
emotion  12606      7  Neutral  3776

🔹 Descriptivo variables cuantitativas:

             count   mean   std  min  25%   50%   75%   max
season     12606.0   2.57  1.11  1.0  2.0   3.0   4.0   4.0
episode    12606.0  13.19  7.20  1.0  7.0  14.0  20.0  25.0
scene      12606.0   7.52  4.43  1.0  4.0   7.0  11.0  29.0
utterance  12606.0   9.80  5.94  1.0  5.0   9.0  14.0  30.0

🔹 Muestra del dataframe:

      season  episode  scene  utterance  emotion
4053       2       12      3         12  Neutral
5498       2       22      8          7   Joyful
2676       1       23     14         10  Neutral
8129       3       19      3         19   Joyful
8911       3       23     12          8   Joyful

#### Conclusiones (friends_emotions)

El dataset presenta una estructura limpia y libre de valores nulos, acotando su alcance analítico exclusivamente a las cuatro primeras temporadas de la serie. Asimismo, la presencia de registros duplicados en las variables de temporada, episodio, escena e incluso en las emociones no interfiere ni afecta negativamente el análisis, ya que responde a la naturaleza lógica y repetitiva de las interacciones y estados anímicos a lo largo de los capítulos, actuando de forma puramente informativa para el estudio de patrones.

#### 4. Dataset: friends_episodes

El dataset presenta una estructura de variables temporales, descriptivas y de rendimiento técnico de los capítulos de la serie.

In [8]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_epiv3)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 236
- Columnas: 9

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year_of_prod    236 non-null    int64
 1   Season          236 non-null    int64
 2   Episode Number  236 non-null    int64
 3   Episode_Title   236 non-null    str
 4   Duration        236 non-null    int64
 5   Summary         236 non-null    str
 6   Director        236 non-null    str
 7   Stars           236 non-null    float64
 8   Votes           236 non-null    int64
dtypes: float64(1), int64(5), str(3)
memory usage: 16.7 KB

🔹 Nulos:
Year_of_prod      0.0
Season            0.0
Episode Number    0.0
Episode_Title     0.0
Duration          0.0
Summary           0.0
Director          0.0
Stars             0.0
Votes             0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

,count,unique,top,freq
Episode_Title,236,232,The One with Ross's Wedding,2
Summary,236,236,"Monica and the gang introduce Rachel to the ""r...",1
Director,236,28,Kevin Bright,54

🔹 Descriptivo variables cuantitativas:

,count,mean,std,min,25%,50%,75%,max
Year_of_prod,236.0,1998.96,2.84,1994.0,1997.00,1999.0,2001.0,2004.0
Season,236.0,5.38,2.81,1.0,3.00,5.0,8.0,10.0
Episode Number,236.0,12.38,6.94,1.0,6.00,12.0,18.0,25.0
Duration,236.0,22.34,1.51,22.0,22.00,22.0,22.0,30.0
Stars,236.0,8.46,0.40,7.2,8.20,8.4,8.7,9.7
Votes,236.0,3369.61,864.43,2557.0,2886.75,3148.5,3583.5,10381.0

🔹 Muestra del dataframe:

,Year_of_prod,Season,Episode Number,Episode_Title,Duration,Summary,Director,Stars,Votes
175,2001,8,6,The One with the Halloween Party,22,Monica and Chandler are having a costume party...,Gary Halvorson,8.5,2969
140,2000,6,20,The One with Mac and C.H.E.E.S.E.,22,Chandler forgets to write down a message for J...,Kevin Bright,7.4,3096
40,1996,2,17,The One Where Eddie Moves In,22,Chandler gets a new roommate. Phoebe gets the ...,Michael Lembeck,8.3,3407
191,2002,8,22,The One Where Rachel Is Late,22,Monica and Phoebe bet on when Rachel's baby wi...,Gary Halvorson,8.3,2662
90,1998,4,18,The One with Rachel's New Dress,22,Rachel has an awkward encounter with Joshua's ...,Gail Mancuso,8.3,3011

#### Conclusiones (friends_episodes)

El dataset presenta una estructura completamente limpia y libre de valores nulos, donde las redundancias identificadas en los títulos resultan normales al corresponder a episodios dobles divididos por partes. No obstante, debido a la existencia de columnas repetidas y a la necesidad de estandarizar las etiquetas de las variables, se contempla como acción clave la modificación y alineación de la estructura para consolidar una base de datos definitiva y optimizada para el análisis.

#### 5. Dataset: friends_escenarios

Este dataset recopila la distribución y el peso visual de las locaciones principales donde se desarrolla la trama de la serie.

In [9]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_escenarios)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 8
- Columnas: 5

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Escenario                8 non-null      str
 1   Tipo                     8 non-null      str
 2   Porcentaje_Escenas_Real  8 non-null      int64
 3   Descripcion              8 non-null      str
 4   Numero_Escenas_Est       8 non-null      int64
dtypes: int64(2), str(3)
memory usage: 452.0 bytes

🔹 Nulos:
Escenario                  0.0
Tipo                       0.0
Porcentaje_Escenas_Real    0.0
Descripcion                0.0
Numero_Escenas_Est         0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

,count,unique,top,freq
Escenario,8,8,Apartamento de Monica,1
Tipo,8,5,Principal,3
Descripcion,8,8,El escenario con más tiempo de pantalla (cocin...,1

🔹 Descriptivo variables cuantitativas:

,count,mean,std,min,25%,50%,75%,max
Porcentaje_Escenas_Real,8.0,12.5,13.01,2.0,3.75,5.5,19.5,38.0
Numero_Escenas_Est,8.0,625.0,650.27,100.0,187.50,275.0,975.0,1900.0

🔹 Muestra del dataframe:

,Escenario,Tipo,Porcentaje_Escenas_Real,Descripcion,Numero_Escenas_Est
0,Apartamento de Monica,Principal,38,El escenario con más tiempo de pantalla (cocin...,1900
3,Pasillo (Hallway),Transición,5,Escenas de transición entre los dos apartament...,250
2,Apartamento de Joey,Principal,18,El apartamento frente al de Monica.,900
6,Oficina/Trabajos,Trabajo,3,"Museo de Ross, oficina de Chandler, Ralph Laur...",150
4,Apartamento de Ross,Secundario,6,"Incluye su apartamento de soltero y el de ""Ugl...",300

#### Conclusiones (friends_escenarios)

El dataset presenta una estructura completamente limpia y un 0% de valores nulos, identificándose que las redundancias en los registros son normales debido a la naturaleza de los datos recopilados. De cara a las próximas fases del proyecto, se plantea llevar a cabo una reestructuración técnica que incluye la modificación y estandarización de los nombres de las columnas, así como la posible eliminación de la variable Tipo, al determinarse que no aporta valor relevante ni impacto significativo para los objetivos del análisis.

#### 6. Dataset: friends_info

Este archivo es una base de datos detallada sobre la emisión original de la serie y su impacto en la audiencia televisiva.

In [10]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_info)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 236
- Columnas: 8

🔹 Info general:

<class 'pandas.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season             236 non-null    int64
 1   episode            236 non-null    int64
 2   title              236 non-null    str
 3   directed_by        236 non-null    str
 4   written_by         236 non-null    str
 5   air_date           236 non-null    str
 6   us_views_millions  236 non-null    float64
 7   imdb_rating        236 non-null    float64
dtypes: float64(2), int64(2), str(4)
memory usage: 14.9 KB

🔹 Nulos:
season               0.0
episode              0.0
title                0.0
directed_by          0.0
written_by           0.0
air_date             0.0
us_views_millions    0.0
imdb_rating          0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

            count unique                          top freq
title         236    227  The One After the Superbowl    2
directed_by   236     30               Gary Halvorson   54
written_by    236    102                  Alexa Junge   11
air_date      236    225                   1995-02-23    2

🔹 Descriptivo variables cuantitativas:

                   count   mean   std    min   25%    50%    75%   max
season             236.0   5.38  2.81   1.00   3.0   5.00   8.00  10.0
episode            236.0  12.38  6.94   1.00   6.0  12.00  18.00  25.0
us_views_millions  236.0  25.37  5.23  15.65  22.3  24.48  27.72  52.9
imdb_rating        236.0   8.46  0.40   7.20   8.2   8.40   8.70   9.7

🔹 Muestra del dataframe:

,season,episode,title,directed_by,written_by,air_date,us_views_millions,imdb_rating
134,6,14,The One Where Chandler Can't Cry,Kevin S. Bright,Andrew Reich & Ted Cohen,2000-02-10,23.80,8.6
50,3,3,The One with the Jam,Kevin S. Bright,Wil Calhoun,1996-10-03,25.20,8.1
27,2,4,The One with Phoebe's Husband,Gail Mancuso,Alexa Junge,1995-10-12,28.10,8.0
44,2,21,The One with the Bullies,Michael Lembeck,Brian Buckner & Sebastian Jones,1996-04-25,24.70,8.2
190,8,21,The One with the Cooking Class,Gary Halvorson,Story by : Dana Klein BorkowTeleplay by : Bria...,2002-05-02,23.97,8.2

#### Conclusiones (friends_info)

El dataset presenta un estado de limpieza óptimo al registrar un 0% de valores nulos, identificándose además que las repeticiones en la columna de títulos son completamente normales al corresponder a episodios dobles divididos por partes. No obstante, de cara a las próximas fases de transformación, se detecta la necesidad de realizar una limpieza exhaustiva en la columna de guionistas (written_by), dado que presenta inconsistencias debidas a la mención de múltiples autores o al uso de términos variantes como "story by", requiriendo una estrategia de estandarización para optimizar su posterior análisis.

#### 7. Dataset: friends_quotes

Este archivo funciona como un registro textual de los diálogos y guiones hablados por los personajes a lo largo de toda la serie.

In [11]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_quotes)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 60291
- Columnas: 6

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 60291 entries, 0 to 60290
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   author          60291 non-null  str
 1   episode_number  60291 non-null  float64
 2   episode_title   60291 non-null  str
 3   quote           60291 non-null  str
 4   quote_order     60291 non-null  float64
 5   season          60291 non-null  float64
dtypes: float64(3), str(3)
memory usage: 2.8 MB

🔹 Nulos:
author            0.0
episode_number    0.0
episode_title     0.0
quote             0.0
quote_order       0.0
season            0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

               count unique          top  freq
author         60291   1024       Rachel  8318
episode_title  60291    226  In Barbados   597
quote          60291  52312        What?   481

🔹 Descriptivo variables cuantitativas:

                  count    mean    std  min   25%    50%    75%    max
episode_number  60291.0   12.42   6.92  1.0   6.0   12.0   18.0   25.0
quote_order     60291.0  141.20  93.53  0.0  67.0  134.0  202.0  597.0
season          60291.0    5.48   2.82  1.0   3.0    6.0    8.0   10.0

🔹 Muestra del dataframe:

,author,episode_number,episode_title,quote,quote_order,season
40925,Ross,18.0,Joey's Award,Mr. Morse I need to talk to you about your mid...,26.0,7.0
1158,Chandler,5.0,The East German Laundry Detergent,"Well, I'm gonna get another espresso. Can I ge...",105.0,1.0
16327,Kate,19.0,The Tiny T-Shirt,"Well, that was ah...",203.0,3.0
41753,Rachel,21.0,The Vows,What?!,128.0,7.0
1332,Phoebe,6.0,The Butt,Based on this play? ...Based on this play!,42.0,1.0

#### Conclusiones (friends_quotes)

El dataset registra un 0% de valores nulos e incluye registros duplicados que se consideran normales, ya que corresponden a múltiples líneas de diálogo de un mismo capítulo y personaje, lo que genera la repetición natural de títulos y nombres. Como acción de mejora, se plantea transformar las variables numéricas de float a entero (int) para optimizar la estructura del archivo sin alterar el análisis.

#### 8. Dataset: friends

Este archivo funciona como un registro cronológico y estructurado de los libretos, diálogos y anotaciones de escena de la serie.

In [12]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_friends)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 67373
- Columnas: 6

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 67373 entries, 0 to 67372
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       67373 non-null  str
 1   speaker    67097 non-null  str
 2   season     67373 non-null  int64
 3   episode    67373 non-null  int64
 4   scene      67373 non-null  int64
 5   utterance  67373 non-null  int64
dtypes: int64(4), str(2)
memory usage: 3.1 MB

🔹 Nulos:
text         0.00000
speaker      0.40966
season       0.00000
episode      0.00000
scene        0.00000
utterance    0.00000
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

         count unique           top  freq
text     67373  56920          Hey!   661
speaker  67097    699  Rachel Green  9312

🔹 Descriptivo variables cuantitativas:

             count   mean    std  min  25%   50%   75%    max
season     67373.0   5.44   2.79  1.0  3.0   5.0   8.0   10.0
episode    67373.0  12.61   6.96  1.0  7.0  13.0  19.0   25.0
scene      67373.0   6.86   4.29  1.0  3.0   6.0  10.0   29.0
utterance  67373.0  18.08  21.15  0.0  6.0  12.0  22.0  255.0

🔹 Muestra del dataframe:

,text,speaker,season,episode,scene,utterance
3861,"OK, turn around. I just don't want you staring...",Ross Geller,1,15,8,22
57319,You said that to me last week.,Chandler Bing,9,8,1,177
1564,I was going for quiet desperation. But if you ...,Joey Tribbiani,1,6,6,14
65856,Ah. All right. But my French was good?,Joey Tribbiani,10,13,11,14
59175,So?,Monica Geller,9,15,7,35

#### Conclusiones (friends)

El dataset demuestra una sólida consistencia al presentarse prácticamente limpio, con la única excepción de la columna speaker, donde las ausencias resultan normales debido a efectos de sonido, reacciones corporales o voces de fondo provenientes de fuentes no registradas. Asimismo, las duplicidades observadas en los registros se consideran habituales e inherentes al contexto de los datos, ya que corresponden a la repetición natural de las variables de ubicación cronológica por cada una de las intervenciones y diálogos que componen el guion de la serie.

#### 9. Dataset: phoebe_buffay_songs

Este archivo funciona como un registro temático y detallado de las composiciones musicales interpretadas por el personaje de Phoebe Buffay a lo largo de la serie.

In [13]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_songs)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 21
- Columnas: 4

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temporada    21 non-null     int64
 1   Episodio     21 non-null     str
 2   Cancion      21 non-null     str
 3   Descripcion  21 non-null     str
dtypes: int64(1), str(3)
memory usage: 804.0 bytes

🔹 Nulos:
Temporada      0.0
Episodio       0.0
Cancion        0.0
Descripcion    0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

            count unique                                  top freq
Episodio       21     18                                 2x06    2
Cancion        21     21                            Your Love    1
Descripcion    21     21  Your love is like a giant pigeon...    1

🔹 Descriptivo variables cuantitativas:

           count  mean   std  min  25%  50%  75%   max
Temporada   21.0  4.19  2.82  1.0  2.0  3.0  6.0  10.0

🔹 Muestra del dataframe:

,Temporada,Episodio,Cancion,Descripcion
4,2,2x06,Terry's a Jerk,Terry's a jerk and he won't let me work!
17,7,7x19,The Shower Song,I'm in the shower and I'm writing a song.
15,6,6x07,Running Song,And the crusty old man said 'I'll do what I can'
2,1,1x23,Babies,They're tiny and chubby and so sweet to touch.
8,3,3x08,Endless Love,Dúo con Chandler.

#### Conclusiones (phoebe_buffay_songs)

El dataset demuestra una excelente integridad al registrar un 0% de valores nulos, identificándose que las duplicidades en los registros son normales y esperadas debido a que el personaje interpreta múltiples canciones dentro de un mismo episodio. Asimismo, el formato actual de la columna Episodio se valida como definitivo al estar alineado intencionalmente con los requerimientos técnicos de la fase de visualización; no obstante, de cara a la estandarización final de la base de datos, se contempla como acción de mejora la traducción y cambio de los títulos de las columnas al idioma inglés.

#### 10. Dataset: apariciones_detalladas_pato_y_pollito
Este archivo funciona como un registro específico y temático centrado en el seguimiento de las mascotas recurrentes de la serie (el pato y el pollito).

In [14]:
#Diagnóstico estructural y descriptivo automatizado del dataset mediante la función info_df para segmentar variables numéricas y categóricas.
trans.info_df(df_pato_pollito)

================================================================================
INFORME TÉCNICO DEL DATAFRAME
================================================================================

🔹 Dimensiones:
- Filas: 21
- Columnas: 4

🔹 Info general:
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Temporada  21 non-null     int64
 1   Episodio   21 non-null     str
 2   Animal     21 non-null     str
 3   Accion     21 non-null     str
dtypes: int64(1), str(3)
memory usage: 804.0 bytes

🔹 Nulos:
Temporada    0.0
Episodio     0.0
Animal       0.0
Accion       0.0
dtype: float64

🔹 Duplicados:
Total duplicados: 0

🔹 Descriptivo variables cualitativas:

         count unique                                        top freq
Episodio    21     13                                       3x22    2
Animal      21      2                                       Pato   12
Accion      21     14  Aparecen en el apartamento de los chicos.    2

🔹 Descriptivo variables cuantitativas:

           count  mean   std  min  25%  50%  75%  max
Temporada   21.0  4.19  0.98  3.0  4.0  4.0  5.0  6.0

🔹 Muestra del dataframe:

,Temporada,Episodio,Animal,Accion
20,6,6x20,Pato,Aparece en una subtrama de Joey.
1,3,3x22,Pollito,Joey y Chandler cuidan de él.
7,4,4x02,Pato,Se traga el anillo de compromiso de Ross.
11,4,4x12,Pato,Se mudan al apartamento de Monica tras la apue...
14,4,4x21,Pato,Joey los cuida mientras los demás están en Lon...

#### Conclusiones (apariciones_detalladas_pato_pollito)

El dataset demuestra una óptima integridad al registrar un 0% de valores nulos, identificándose que las repeticiones en las variables son completamente normales y esperadas; esto se debe a que la columna Animal se limita a dos únicos sujetos (el pato y el pollito) y a que la columna Accion describe de forma idéntica el contexto de la escena para ambos cuando interactúan juntos. Asimismo, se valida que el formato de la columna Episodio es el definitivo por responder de manera intencional a los requerimientos técnicos de la fase de visualización, contemplándose como única acción de mejora la traducción y cambio de los nombres de las columnas al idioma inglés.

# Conclusiones finales del EDA

- Calidad de Datos: Integridad excelente con un 0% de nulos en la mayoría de los archivos. La única excepción está en la columna speaker de los guiones, lo cual es normal ya que representa sonidos de fondo, reacciones corporales o voces ambientales no registradas.

- Duplicados: Las repeticiones no son errores; se justifican por la estructura lógica de los datos (episodios dobles, personajes que cantan varias canciones en un mismo capítulo o escenas donde el pato y el pollito interactúan juntos bajo una misma descripción, etc).

- Optimización de Tipos y Limpieza: Se plantea transformar las variables numéricas de orden de float a entero (int) para mejorar la estructura. Asimismo, se detecta la necesidad de limpiar y estandarizar la columna written_by (escrito por) en el dataset de información, debido a la presencia de múltiples autores y variantes de texto como "story by".

- Estandarización y Visualización: Se valida el formato de la columna Episodio (ej. 1x01) por ser idóneo para el diseño de tableros. Como acción final, se propone eliminar columnas no relevantes (como Tipo en escenarios) y traducir los encabezados al inglés para unificar todo el proyecto. Estandarizar idiomas en las columas (Temporada ~ Season), minúscula & mayúscula

- Los datasets son complementarios y combinables, salvo: apariciones_detalladas_pato_y_pollito, bodas_divorcios_de_ross, cameos_friends_completos, friends_escedarios y phoebe_buffay_songs.

Esta fase permite definir claramente los pasos de la siguiente etapa: limpieza y transformación.

bodas_divorcio_ross:
1. el nombre del fichero en inglés
2. Personaje -> author
3. evento -> event
4. Temporada -> Season
5. Detalle -> Detail
6. todas las columnas en minusculas

 

cameos_friends_completo
1. el nombre del fichero
2. Actor/Actriz --> Actor
3. Personaje -> Author
4. Descripción/Temporada 
  Split celdas para tener dos columnas
  Descripción -> Details
  Temporada -> Season
5. todas las columnas en minusculas

 

friends_emotions --> todo ok

 

 

friends_episodes
1. todas las columnas en minusculas
2. Episode Number -> episode
3. Episode Title -> title

 

friends_escenarios
1. el nombre del fichero en inglés
2. Escenario -> set
3. Tipo -> 
4. Porcentaje_escenas_real ->
5. Descripción -> Detail
6. Numero_escenas_est ->

 

 

friends_info --> todo ok

 

friends_quotes 
1. Episode_number --> episode
3. Episode_Title -> title

 

friends --> todo ok

 

phoebe_buffay_songs

 

1. todas las columnas en minuscula
2. Temporada -> season
3. Episodio -> episode
4. Cancion -> song
5. Descripción -> detail

 

apariciones_detalladas_pato_y_pollito
1. cambiar el nombre fichero
2. todas las columnas en minuscula
3. Temporada -> season
4. Episodio -> episode
5. Animal -> animal
6. Accion -> Detail (?)